config/routes.rb
Chef::Application.routes.draw do
  resources :orders
  resources :sessions
  namespace :admin do
    resources :orders
    resources :meal_types
    resources :locations
  end
  
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

  match 'new_mass_order' => 'orders#new_mass_order'
  match 'create_mass_order' => 'orders#create_mass_order'

  root :to => 'orders#index'
end

app/controllers/admin/meal_types_controller.rb
class Admin::MealTypesController < ApplicationController
  before_filter :admin_required
  # GET /meal_types
  # GET /meal_types.json
  def index
    @meal_types = MealType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meal_types }
    end
  end

  # GET /meal_types/1
  # GET /meal_types/1.json
  def show
    @meal_type = MealType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal_type }
    end
  end

  # GET /meal_types/new
  # GET /meal_types/new.json
  def new
    @meal_type = MealType.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal_type }
    end
  end

  # GET /meal_types/1/edit
  def edit
    @meal_type = MealType.find(params[:id])
  end

  # POST /meal_types
  # POST /meal_types.json
  def create
    @meal_type = MealType.new(params[:meal_type])

    respond_to do |format|
      if @meal_type.save
        format.html { redirect_to admin_meal_types_path, notice: 'Maaltidstype ble opprettet.' }
        format.json { render json: @meal_type, status: :created, location: @meal_type }
      else
        format.html { render action: "new" }
        format.json { render json: @meal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meal_types/1
  # PUT /meal_types/1.json
  def update
    @meal_type = MealType.find(params[:id])

    respond_to do |format|
      if @meal_type.update_attributes(params[:meal_type])
        format.html { redirect_to admin_meal_types_path, notice: 'Maaltidstype ble oppdatert.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_types/1
  # DELETE /meal_types/1.json
  def destroy
    @meal_type = MealType.find(params[:id])
    @meal_type.destroy

    respond_to do |format|
      format.html { redirect_to meal_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meal_types_helper.rb
module MealTypesHelper
end

app/views/admin/meal_types/_form.html.erb
<%= form_for [:admin, @meal_type]  do |f| %>
  <% if @meal_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal_type.errors.count, "error") %> prohibited this meal_type from being saved:</h2>

      <ul>
      <% @meal_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-4">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
</div>

<div class="row">
  <div class="actions col-md-4">
    <%= f.submit class:"btn btn-primary col-md-6"%>
  </div>
</div>
<p>
  &nbsp;
</p>
<% end %>

app/views/admin/meal_types/edit.html.erb
<h1>Rediger måltidstype</h1>

<%= render 'form' %>

app/views/admin/meal_types/index.html.erb
<h1 class="span12">Måltidstyper</h1>
<h4 class="span12">Det er ikke mulig å slette måltidstyper under festivalen. Hvis det er nødvendig å deaktivere en måltidstype, <br/>så gi det nytt navn "-----" så skjønner folk at de ikke skal velge det.</h4>
<table class="table table-hover span12">
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meal_types.each do |admin_meal_type| %>
  <tr>
    <td><%= admin_meal_type.title %></td>
    <td><%= link_to 'Vis', admin_meal_type_path(admin_meal_type) %></td>
    <td><%= link_to 'Rediger', edit_admin_meal_type_path(admin_meal_type) %></td>
  </tr>
<% end %>
</table>

<br />
<div class="span-12">
  <%= link_to new_admin_meal_type_path, class:"btn btn-success" do %>
    <i class="glyphicon glyphicon-plus"></i> Ny måltidstype
  <% end %>
  <p>&nbsp;</p>
</div>

app/views/admin/meal_types/new.html.erb
<h1>Ny måltidstype</h1>

<%= render 'form' %>

app/views/admin/meal_types/show.html.erb
<p id="notice"><%= notice %></p>

<div><%= @meal_type.title %></div>

<%= link_to 'Rediger', edit_admin_meal_type_path(@meal_type) %> |
<%= link_to 'Tilbake', admin_meal_types_path %>