config/routes.rb
Chef::Application.routes.draw do
  resources :orders
  resources :sessions
  namespace :admin do
    resources :orders
    resources :meal_types
    resources :locations
  end
  
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

  match 'new_mass_order' => 'orders#new_mass_order'
  match 'create_mass_order' => 'orders#create_mass_order'

  root :to => 'orders#index'
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :name
  has_many :orders
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /meal_types/1
  # GET /meal_types/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def create
    @location = Location.new(params[:location])

      if @location.save
        redirect_to admin_locations_path, notice: 'Leveringssted ble lagt til'
      else
        render action: "new"
      end
  end

  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to admin_locations_path, notice: 'Leveringssted ble lagt til.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to meal_types_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/views/admin/locations/_form.html.erb
<%= form_for [:admin, @location]  do |f| %>
    <% if @location.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@location.errors.count, "error") %> prohibited this from being saved:</h2>

          <ul>
            <% @location.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
<div class="row">
  <div class="col-md-4">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <%= f.label :address %>
    <%= f.text_area :address, rows:3 %>
  </div>
</div>
    <div class="row">
      <div class="actions col-md-4">
        <%= f.submit class:"btn btn-primary col-md-6"%>
      </div>
    </div>
    <p>
      &nbsp;
    </p>
<% end %>

app/views/admin/locations/edit.html.erb
<h1>Rediger leveringssted</h1>

<%= render 'form' %>

app/views/admin/locations/index.html.erb
<h1 class="span12">Leveringssteder</h1>
<h4 class="span12">Det er ikke mulig å slette leveringssteder under festivalen. Hvis det er nødvendig å deaktivere et leveringssted, <br/>så gi det nytt navn "-----" så skjønner folk at de ikke skal velge det.</h4>
<table class="table table-hover span12">
  <tr>
    <th>Navn</th>
    <th>Addresse</th>
    <th></th>
    <th></th>
  </tr>

  <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.address %></td>
        <td><%= link_to 'Rediger', edit_admin_location_path(location) %></td>
      </tr>
  <% end %>
</table>

<br />
<div class="span-12">
  <%= link_to new_admin_location_path, class:"btn btn-success" do %>
      <i class="glyphicon glyphicon-plus"></i> Nytt leveringssted
  <% end %>
  <p>&nbsp;</p>

</div>

app/views/admin/locations/new.html.erb
<h1 class="span12">Nytt leveringssted</h1>

<%= render 'form' %>