config/routes.rb
Chef::Application.routes.draw do
  resources :orders
  resources :sessions
  namespace :admin do
    resources :orders
    resources :meal_types
    resources :locations
  end
  
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

  match 'new_mass_order' => 'orders#new_mass_order'
  match 'create_mass_order' => 'orders#create_mass_order'

  root :to => 'orders#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :delivered_at, :meals_attributes, :amount, :deliver_to, :comment, :location_id, :workshop_name
  has_many :meals
  has_many :meal_types, through: :meals
  belongs_to :location
  belongs_to :user
  accepts_nested_attributes_for :meals
  validates_presence_of :delivered_at, :message => "can't be empty"



  def self.to_be_delivered_on(date)
    self.where("delivered_at >= ? AND delivered_at <= ?", date, date+1)
  end

  def total_order_amount
    meals.sum(:amount)
  end

  def self.orders_by_location(location_id)
    self.where("location_id = ?",location_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_filter :admin_required

  def index
    redirect_to admin_order_path("2015-02-05")
  end

  def show
    @orders = Order.to_be_delivered_on(Date.parse(params[:id]))
    @locations = Location.all
    @total = 0
    @meal_types = MealType.all.map do |m|
      tot = m.amount_ordered_for_day(Date.parse(params[:id]))
      @total += tot
      [m.title, tot]
    end

    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        if !params[:location].nil?
          @total = 0
          @meal_types = MealType.all.map do |m|
            tot = m.amount_ordered_for_day_by_location(Date.parse(params[:id]),params[:location])
            @total += tot
            [m.title, tot]
          end
        end
        pdf = OrderPdf.new(@orders, @meal_types, params[:id], @total,params[:location])
        send_data pdf.render, filename:"orders",type: "application/pdf",
          disposition: "inline"
      end
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :login_required
  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = find_order(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.meals << Meal.new
    @meal_types = MealType.all.collect {|p| [ p.title, p.id ] }
    @locations = Location.all.collect {|p| [ p.name, p.id ] }
  end

  def new_mass_order
    @order = Order.new
    @order.meals << Meal.new
    @meal_types = MealType.all.collect {|p| [ p.title, p.id ] }
    @locations = Location.all.collect {|p| [ p.name, p.id ] }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  def create_mass_order
    @order = Order.new(params[:order])
    @order.user = current_user
    dates = Rails.application.config.workshop_dates
    @order.delivered_at = DateTime.parse(dates[0])
    @meal_types = MealType.all.collect {|p| [ p.title, p.id ] }
    @locations = Location.all.collect {|p| [ p.name, p.id ] }
    orders_saved = false

    dates.each do |date_string|
      o = Order.new
      o.deliver_to = @order.deliver_to
      o.location = @order.location
      o.delivered_at = DateTime.parse(date_string)
      o.user = @order.user
      o.comment = @order.comment
      @order.meals.each do |m|
        a = Meal.new
        a.amount = m.amount
        a.meal_type_id = m.meal_type_id
        o.meals << a
      end
      if o.save
        orders_saved = true
      else
        orders_saved = false
        @order.errors[:base] << "Ett av feltene inneholder ugyldig data"
        break
      end
    end

      if orders_saved
        redirect_to orders_path, notice: 'Ordrer opprettet'
      else
        render action: "new_mass_order"
      end
  end

  # GET /orders/1/edit
  def edit
    @order = find_order(params[:id])
    params[:date] = @order.delivered_at
    @meal_types = MealType.all.collect {|p| [ p.title, p.id ] }
    @locations = Location.all.collect {|p| [ p.name, p.id ] }
  end

  # POST /orders
  def create
    if(params[:date].blank?)
      @order = Order.new(params[:order])
      @order.user = current_user
      @meal_types = MealType.all.collect {|p| [ p.title, p.id ] }
      @locations = Location.all.collect {|p| [ p.name, p.id ] }
      @order.errors[:base] << "Ugyldig dato"
      render :action => 'new'
      return
    end
    date = DateTime.parse(params[:date])
    params[:order]["delivered_at(1i)"] = date.year.to_s
    params[:order]["delivered_at(2i)"] = date.mon.to_s
    params[:order]["delivered_at(3i)"] = date.mday.to_s
    params[:order]["delivered_at(4i)"] = '12' ##Remove to restore time functionality
    params[:order]["delivered_at(5i)"] = '00' ##Remove to restore time functionality
    @order = Order.new(params[:order])
    @order.user = current_user
    @meal_types = MealType.all.collect {|p| [ p.title, p.id ] }
    @locations = Location.all.collect {|p| [ p.name, p.id ] }

    if @order.save
      redirect_to @order, notice: 'Ordre ble opprettet.'
    else
      render :action => 'new'
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = find_order(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Ordre ble oppdatert.' }
        format.json { head :no_content }
      else
        format.html { redirect_to action: "edit", error: "Ugyldige endringer"  }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = find_order(params[:id])
    date = @order.delivered_at.strftime("%Y-%m-%d")
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Ordre ble slettet' }
      format.json { head :no_content }
    end
  end

  def find_order(order_id)
    if current_user.admin?
      Order.find(params[:id])
    else
      current_user.orders.find(params[:id])
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def tab_by_location(orders,location)
    ret = ''
    orders.each do |order|
      if order.location.name == location.name
        ret += order.user.given_name + " " + order.user.family_name
        ret += order.delivered_at.strftime("%a, %d. %b")
        ret += order.created_at.strftime("%a, %d. %b")
      end
    end
    ret
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-danger" >
      <h2><%= @order.errors.count %> feil må rettes opp før orderen blir lagret:</h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row col-md-8">
<div class="row">


  <div class="col-md-12" style="padding-right: 0px">
    <h4>Mattyper og mengde</h4>
    <%= f.fields_for :meals do |meal| %>
      <%= render 'meal_fields', f: meal %>
    <% end %>
  </div>

  <p class="col-md-12" style="padding-right: 0px">

  <%= link_to_add_fields "Legg til enda et måltid", f, :meals %>
  </p>
</div>
<div class="row">
  <h4 class="col-md-12">Leveringssted og tidspunkt</h4>
  <div class="col-md-6">
    <%= f.select :location_id, @locations %>
    <%= f.text_area :deliver_to, rows:4, placeholder:"Spesifikk leveringsadresse (Valgfri)" %>
  </div>

  <div class="col-md-6">
    <p>
    <%= text_field_tag :date, nil, placeholder:"Leveringsdag",class:"datepicker" %>
    </p>
    <p>
    <%#= f.time_select :delivered_at, {minute_step: 15, default: DateTime.new(2015,2,14,12,00), :time_separator => ''}, class:"input-small", :style => 'width: 50%;float:left' %>
    </p>
    <br />
    <p>
      <%= f.text_field :workshop_name, :placeholder => "Workshopnavn (Bare for WOKer)", :style => 'margin-top: 28px' %>
    </p>
  </div>

</div>
<div class="row" style="margin-top: 15px">
    <div class="col-md-12">
      <%= f.text_area :comment, rows:3, placeholder:"Kommentar" %>
    </div>
</div>
<div class="row col-md-12">
  <div class="col-md-12" style="padding-left: 0px">
    <p>&nbsp;</p>
    <%= f.submit "Lever bestilling", class:"btn btn-primary col-md-4"%>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
  </div>
</div>
</div>
    <div class="col-md-4">
      <div class="well">
        <h4>Bestillingsinfo</h4>
        Lunsj serveres i tidsrommet kl 12-13<br />
        Middag serveres i tidsrommet kl 16-18<br />
        <br />
        <b>Unntaksdager</b><br />
        <table class="table">
          <tr><td>05.02</td><td>Ingen matbestilling</td></tr>
          <tr><td>09.02</td><td>Dalai Lama: Lunsj 11-12</td></tr>
          <tr><td>10.02</td><td>Skidag: Middag 17-19</td></tr>
          <tr><td>12.02</td><td>Walk of Peace: Lunsj 11-12. <br />Middag 15.30-16.30</td></tr>
          <tr><td>15.02</td><td>Avslutningsdag. Middag 15-16</td></tr>
        </table>
        Deltakere spiser lunsj i Workshop og middag i Hangaren.<br />
        Frivillige spiser lunsj og middag på Bodegaen, Samfundet.<br />
        <br />
        Mat må bestilles senest kl 12 dagen før levering.<br />
        Middag og lunsj må bestilles på separate ordrer.<br />
        <br />
      </div>

    </div>
<% end %>
<script>
  $('.datepicker').datepicker({
    startDate:new Date(2015,1,5),
    endDate:new Date(2015,1,16),
    format: 'yyyy-mm-dd',
    autoclose: true
  });
</script>

app/views/orders/_mass_form.html.erb
<%= form_for(@order, url: create_mass_order_path, :html => { :class => "form-vertical" }) do |f| %>
    <% if @order.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= @order.errors.count %> feil må rettes opp før orderen blir lagret:</h2>
          <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
<div class="row">


    <div class="col-md-8" style="padding-right: 0px">
      <h4>Mattyper og mengde</h4>
      <%= f.fields_for :meals do |meal| %>
          <%= render 'meal_fields', f: meal %>
      <% end %>
    </div>

    <p class="col-md-8" style="padding-right: 0px">
      <%= link_to_add_fields "Legg til enda et måltid", f, :meals %>
    </p>
</div>
    <div class="row">
      <h4 class="col-md-12">Leveringssted</h4>
      <div class="col-md-4">
        <%= f.select :location_id, @locations %>
        <%= f.text_area :deliver_to, rows:4, placeholder:"Spesifikk leveringsadresse (Valgfri)" %>
      </div>
      <div class="col-md-4">
        <p>
          <%= f.text_field :workshop_name, :placeholder => "Workshopnavn (Bare for WOKer)" %>
        </p>
      </div>
    </div>
    <div class="row" style="margin-top: 15px">
      <div class="col-md-8">
        <%= f.text_area :comment, rows:3, placeholder:"Kommentar" %>
      </div>
    </div>


    <div class="col-md-12" style="padding-left: 0px">
      <p>&nbsp;</p>
      <%= f.submit "Lever bestilling", class:"btn btn-primary col-md-2"%>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
    </div>
<% end %>

app/views/orders/_meal_fields.html.erb
<div class="control-group controls">
  <div class="col-md-6" style="padding-left:0px; padding-top: 5px; padding-bottom: 5px; padding-right: 22px">
  <%= f.text_field :amount, placeholder:"Antall, (1 per person)"%>
  </div>
  <div class="col-md-6" style="padding-top: 5px; padding-bottom: 5px; padding-left: 8px">
  <%= f.select :meal_type_id, @meal_types %>
  </div>
</div>

app/views/orders/edit.html.erb
<h1 class="span12">Rediger bestilling</h1>

<%= render 'form' %>

app/views/orders/index.html.erb
<% if logged_in? && !current_user.regular_user? %>
<br />
    <div class="alert alert-danger">
  Du har ikke tilgang til å bestille mat. Denne tilgangen er normalt gitt til alle nestledere. <br />
  Hvis du likevel trenger tilgang, så kan du kontakte orakel@isfit.org.
</div>
<% end %>
<h1 class="col-md-12">Mine bestillinger</h1>
<% unless @orders.count == 0 %>
<table class="table table-hover col-md-12">
  <thead>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tbody>
  <% @orders.each do |order| %>
    <% if order.location.nil? %>
        <% next %>
    <% end %>
    <th><h2><%= link_to 'Ordre# ' + order.id.to_s, order %></h2></th>
    <tr><td></td></tr>
    <th>Leveringsadresse:</th>
    <th>Leveringsdag:</th>
    <tr>
      <td><%= link_to order.location.name, order%></td>
      <td><%= link_to order.delivered_at.strftime("%a %d. %b"), order %></td>
      <td class="btn-group" >
          <%= link_to edit_order_path(order), class:"btn" do %>
            <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-pencil"></span>
            </button>
          <%end%>
          <%= link_to order, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn" do %>
            <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-trash"></span>
            </button>
          <% end %>
      </td>
    </tr>
    <th></th>
    <th>Måltid</th>
    <th>Antall</th>
    <% order.meals.each do |meal| %>
      <tr>
        <td></td>
        <td><%= meal.meal_type.title %></td>
        <td><%= meal.amount %></td>
      </tr>
    <% end %>
  <% end %>
</tbody>
</table>
<% else %>
  <div class="alert alert-info col-md-12">
  <h4>Ingen bestillinger</h4>
  Du har ikke registert noen bestillinger.
    <% if logged_in? && current_user.regular_user? %>
  <%= link_to "Bestill mat.", new_order_path %>
        <% end %>
    <p>&nbsp;</p>
</div>
<% end %>

app/views/orders/new.html.erb
<h1 class="span12">Ny matbestilling</h1>

<%= render 'form' %>

app/views/orders/new_mass_order.html.erb
<h1 class="span12">Lag bestillinger for hele festivalen</h1>
<p class="span11">Med dette skjemaet kan du opprette matbestillinger for alle workshopdagene inkl. fridagen. Når du fyller ut skjemaet blir det opprettet én bestilling for hver dag, alle med samme informasjon. Du kan om ønskelig redigere de enkeltvis etterpå. Merk at dette skjemaet ikke sletter eksisterende bestillinger hvis det brukes flere ganger.</p>

<%= render 'mass_form' %>

app/views/orders/show.html.erb
<p class="btn-group span3 pull-right" >
  <%= link_to edit_order_path(@order), class:"btn" do %>
    <i class="glyphicon glyphicon-pencil"></i> Rediger
  <%end%>
  <%= link_to @order, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn" do %>
    <i class="glyphicon glyphicon-trash"></i> Slett
  <% end %>
</p>
</p>
<h1>Ordre# <%= @order.id %></h1>
<table class="table span11">
  <tr>
    <th>Leveringsadresse</th>
    <th>Leveringsdato</th>
  </tr>
  <tr>
    <td>
      <h3><%= link_to @order.user.given_name + " " + @order.user.family_name, "http://internal.isfit.org/users/#{@order.user.id}" %></h3>
      <h3><%= simple_format(@order.location.name) %></h3>
      <h3><%= simple_format(@order.location.address) %></h3>
      <h3><%= simple_format(@order.deliver_to) %></h3>
    </td>
    <td>
      <h2><%= @order.delivered_at.strftime("%a, %d. %b") %></br>
        <%#= @order.delivered_at.strftime("%H:%M") %></h2>
    </td>
  </tr>
</table>

<table class="table span11">
  <tr>
    <th>Totalt antall</th>
    <th><%= @order.total_order_amount %></th>
  </tr>
  <tr>
    <th>Måltid:</th>
    <th>Mengde:</th>
  </tr>

  <% @order.meals.each do |meal| %>
    <tr>
      <td><%= meal.meal_type.title %></td>
      <td><%= meal.amount %></td>
      <tr>
      <% end %>
    </table>